// Decompiled with JetBrains decompiler
// Type: PafLauncherEditor.RegistryParser
// Assembly: PAFLauncherEditor, Version=5.0.1.0, Culture=neutral, PublicKeyToken=null
// MVID: 5FA988B0-28E9-47EB-9AB7-80FDA0B74460
// Assembly location: G:\csharp\PortableAppGen\Reference\%DEFAULT FOLDER%\PAFLauncherEditor.exe

using System;
using System.Collections.Generic;
using System.Linq;

namespace PafLauncherEditor
{
  internal static class RegistryParser
  {
    private static List<string> _keys = new List<string>();

    public static List<string> Keys
    {
      get
      {
        return RegistryParser._keys;
      }
      set
      {
        RegistryParser._keys = value;
      }
    }

    public static bool KeyIsValid(string key)
    {
      if (!RegistryParser.KeyIsVoidOfKeywords(key) || RegistryParser.KeyIsFlagged(key))
        return false;
      RegistryParser.Keys.Add(key);
      return true;
    }

    private static bool KeyIsVoidOfKeywords(string key)
    {
      return !new List<string>()
      {
        "\\INSTALLER\\",
        "\\UNINSTALL\\",
        "\\ENUM\\",
        "\\SHELLNOROAM\\",
        "\\SYSTEM\\CURRENTCONTROLSET\\",
        "\\MSISERVER\\",
        "\\IMSISERVER\\"
      }.Any<string>(new Func<string, bool>(key.Trim().ToUpper().Contains));
    }

    private static bool KeyIsFlagged(string key)
    {
      return new List<string>()
      {
        "HKCU\\SESSIONINFORMATION\\PROGRAMCOUNT",
        "HKCU\\SOFTWARE\\MICROSOFT\\CRYPTOGRAPHY\\RNG\\SEED",
        "HKCU\\SOFTWARE\\MICROSOFT\\DIRECTDRAW\\MOSTRECENTAPPLICATION",
        "HKCU\\SOFTWARE\\MICROSOFT\\SCHEDULINGAGENT",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\FILEEXTS",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\GROUP POLICY",
        "HKCU\\SOFTWARE\\CLASSES\\LOCAL SETTINGS\\MUICACHE",
        "HKCU\\SOFTWARE\\CLASSES\\LOCAL SETTINGS\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\TRAYNOTIFY",
        "HKCU\\SOFTWARE\\CLASSES\\LOCAL SETTINGS\\SOFTWARE\\MICROSOFT\\WINDOWS\\SHELL",
        "HKCU\\SOFTWARE\\CLASSES\\WOW6432NODE\\LOCAL SETTINGS\\SOFTWARE\\MICROSOFT\\WINDOWS\\SHELL",
        "HKCU\\SOFTWARE\\MICROSOFT\\DIRECT3D\\MOSTRECENTAPPLICATION",
        "HKCU\\SOFTWARE\\MICROSOFT\\DIRECTINPUT\\MOSTRECENTAPPLICATION",
        "HKCU\\SOFTWARE\\MICROSOFT\\INTERNET EXPLORER\\INTERNATIONAL\\CPMRU",
        "HKCU\\SOFTWARE\\MICROSOFT\\INTERNET EXPLORER\\TYPEDURLS",
        "HKCU\\SOFTWARE\\MICROSOFT\\MEDIAPLAYER\\HEALTH",
        "HKCU\\SOFTWARE\\MICROSOFT\\MULTIMEDIA\\ACTIVEMOVIE",
        "HKCU\\SOFTWARE\\MICROSOFT\\RESTARTMANAGER",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS MAIL",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS NT\\CURRENTVERSION\\TASKMANAGER",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\ACTION CENTER\\CHECKS",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\ACTION CENTER\\PROVIDERS\\EVENTLOG",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\APPLETS",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\COMDLG32",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\DISCARDABLE",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\MENUORDER",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\MOUNTPOINTS2",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\RECENTDOCS",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\RUNMRU",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\SESSIONINFO",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\STARTPAGE",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\STREAMMRU",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\STREAMS",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\TRAYNOTIFY",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\EXPLORER\\USERASSIST",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\INTERNET SETTINGS\\5.0\\CACHE",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\INTERNET SETTINGS\\CACHE",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\INTERNET SETTINGS\\CONNECTIONS",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\INTERNET SETTINGS\\USER AGENT\\POST PLATFORM",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\MUILANGUAGES\\FILEVERSIONS",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\SHELL EXTENSIONS\\CACHED",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\WINDOWSUPDATE",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\SHELL",
        "HKCU\\SOFTWARE\\MICROSOFT\\WINDOWS\\SHELLNOROAM",
        "HKCU_CLASSES",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\RELIABILITY",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\SERVICES\\*\\ENUM",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\SERVICES\\SHAREDACCESS",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\SERVICES\\SWMIDI",
        "HKLM\\BCD00000000",
        "HKLM\\COMPONENTS",
        "HKLM\\DRIVERS",
        "HKLM\\HARDWARE",
        "HKLM\\SAM",
        "HKLM\\SCHEMA",
        "HKLM\\SECURITY",
        "HKLM\\SOFTWARE\\CLASSES\\LOCAL SETTINGS\\SOFTWARE\\MICROSOFT\\WINDOWS\\SHELL",
        "HKLM\\SOFTWARE\\MICROSOFT\\DFRG",
        "HKLM\\SOFTWARE\\MICROSOFT\\DIRECT3D\\MOSTRECENTAPPLICATION",
        "HKLM\\SOFTWARE\\MICROSOFT\\DIRECTDRAW\\MOSTRECENTAPPLICATION",
        "HKLM\\SOFTWARE\\MICROSOFT\\EVENTSYSTEM\\{26C409CC-AE86-11D1-B616-00805FC79216}\\SUBSCRIPTIONS",
        "HKLM\\SOFTWARE\\MICROSOFT\\RELIABILITY ANALYSIS",
        "HKLM\\SOFTWARE\\MICROSOFT\\UPDATES\\UPDATEEXEVOLATILE",
        "HKLM\\SOFTWARE\\MICROSOFT\\WBEM\\PROVIDERS\\PERFORMANCE",
        "HKLM\\SOFTWARE\\MICROSOFT\\WBEM\\TRANSPORTS\\DECOUPLED",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS DEFENDER",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS NT\\CURRENTVERSION\\PERFLIB",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS NT\\CURRENTVERSION\\PREFETCHER",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS NT\\CURRENTVERSION\\SCHEDULE\\TASKCACHE",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS NT\\CURRENTVERSION\\SUPERFETCH",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS NT\\CURRENTVERSION\\SYSTEMRESTORE",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS SEARCH",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\COMPONENT BASED SERVICING",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\DIAGNOSTICS",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\GROUP POLICY\\SERVICEINSTANCES",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\GROUP POLICY\\STATE\\MACHINE\\EXTENSION-LIST\\{00000000-0000-0000-0000-000000000000}",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\MS-DOS EMULATION",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\RELIABILITY",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\SIDEBYSIDE",
        "HKLM\\SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\WINDOWSUPDATE",
        "HKLM\\SOFTWARE\\WOW6432NODE\\MICROSOFT\\DIRECT3D\\MOSTRECENTAPPLICATION",
        "HKLM\\SOFTWARE\\WOW6432NODE\\MICROSOFT\\DIRECTDRAW\\MOSTRECENTAPPLICATION",
        "HKLM\\SOFTWARE\\WOW6432NODE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\GROUP POLICY\\SERVICEINSTANCES",
        "HKLM\\SOFTWARE\\WOW6432NODE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\GROUP POLICY\\STATE\\MACHINE\\EXTENSION-LIST\\{00000000-0000-0000-0000-000000000000}",
        "HKLM\\SYSTEM\\CONTROLSET001",
        "HKLM\\SYSTEM\\CONTROLSET002",
        "HKLM\\SYSTEM\\CONTROLSET003",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\CMF",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\CRITICALDEVICEDATABASE",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\DEVICECLASSES",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\DIAGNOSTICS",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\HIVELIST",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\NSI",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\SESSION MANAGER\\APPCOMPATCACHE",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\SESSION MANAGER\\APPCOMPATIBILITY",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\SESSION MANAGER\\MEMORY MANAGEMENT\\PREFETCHPARAMETERS",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\CONTROL\\SESSION MANAGER\\POWER",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\ENUM\\ACPI",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\ENUM\\ACPI_HAL",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\ENUM\\PCI",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\ENUM\\PCIIDE",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\ENUM\\ROOT",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\ENUM\\STORAGE",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\ENUM\\USB",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\SERVICES\\KMIXER",
        "HKLM\\SYSTEM\\CURRENTCONTROLSET\\SERVICES\\VSS",
        "HKLM\\SYSTEM\\LASTKNOWNGOODRECOVERY",
        "HKLM\\SYSTEM\\MOUNTEDDEVICES"
      }.Any<string>((Func<string, bool>) (k => k.Equals(key.Trim().ToUpper(), StringComparison.OrdinalIgnoreCase)));
    }
  }
}
